package com.InteInfo.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commonlymenu generated by hbm2java
 */
@Entity
@Table(name = "commonlymenu", catalog = "interinfo")
public class Commonlymenu implements java.io.Serializable {

	private Integer commonid;
	private Menu menu;
	private User user;

	public Commonlymenu() {
	}

	public Commonlymenu(Menu menu, User user) {
		this.menu = menu;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "commonid", unique = true, nullable = false)
	public Integer getCommonid() {
		return this.commonid;
	}

	public void setCommonid(Integer commonid) {
		this.commonid = commonid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menuid")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
