package com.InteInfo.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WfCondition generated by hbm2java
 */
@Entity
@Table(name = "wf_condition", catalog = "interinfo")
public class WfCondition implements java.io.Serializable {

	private Integer conditionId;
	private String conditionName;
	private String conditionSymbol;
	private String compareValue;
	private Boolean conditionStatus;
	private Set<WfLine> wfLines = new HashSet<WfLine>(0);

	public WfCondition() {
	}

	public WfCondition(String conditionName, String conditionSymbol, String compareValue, Boolean conditionStatus,
			Set<WfLine> wfLines) {
		this.conditionName = conditionName;
		this.conditionSymbol = conditionSymbol;
		this.compareValue = compareValue;
		this.conditionStatus = conditionStatus;
		this.wfLines = wfLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ConditionID", unique = true, nullable = false)
	public Integer getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(Integer conditionId) {
		this.conditionId = conditionId;
	}

	@Column(name = "ConditionName", length = 100)
	public String getConditionName() {
		return this.conditionName;
	}

	public void setConditionName(String conditionName) {
		this.conditionName = conditionName;
	}

	@Column(name = "ConditionSymbol", length = 20)
	public String getConditionSymbol() {
		return this.conditionSymbol;
	}

	public void setConditionSymbol(String conditionSymbol) {
		this.conditionSymbol = conditionSymbol;
	}

	@Column(name = "CompareValue", length = 50)
	public String getCompareValue() {
		return this.compareValue;
	}

	public void setCompareValue(String compareValue) {
		this.compareValue = compareValue;
	}

	@Column(name = "ConditionStatus")
	public Boolean getConditionStatus() {
		return this.conditionStatus;
	}

	public void setConditionStatus(Boolean conditionStatus) {
		this.conditionStatus = conditionStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfCondition")
	public Set<WfLine> getWfLines() {
		return this.wfLines;
	}

	public void setWfLines(Set<WfLine> wfLines) {
		this.wfLines = wfLines;
	}

}
