package com.InteInfo.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WfMember generated by hbm2java
 */
@Entity
@Table(name = "wf_member", catalog = "interinfo")
public class WfMember implements java.io.Serializable {

	private Integer memberId;
	private WfGroup wfGroup;
	private String memberCode;
	private String memberName;

	public WfMember() {
	}

	public WfMember(WfGroup wfGroup) {
		this.wfGroup = wfGroup;
	}

	public WfMember(WfGroup wfGroup, String memberCode, String memberName) {
		this.wfGroup = wfGroup;
		this.memberCode = memberCode;
		this.memberName = memberName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MemberID", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false)
	public WfGroup getWfGroup() {
		return this.wfGroup;
	}

	public void setWfGroup(WfGroup wfGroup) {
		this.wfGroup = wfGroup;
	}

	@Column(name = "MemberCode", length = 100)
	public String getMemberCode() {
		return this.memberCode;
	}

	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}

	@Column(name = "MemberName", length = 100)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

}
