package com.inter.info.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "interinfo")
public class User implements java.io.Serializable {

	private Integer userid;
	private Role role;
	private String staffid;
	private String username;
	private String userpassword;
	private String email;
	private Boolean islocked;
	private Boolean status;
	private Date createdate;
	private String createby;
	private Date updatedate;
	private String updateby;
	private Set<Commonlymenu> commonlymenus = new HashSet<Commonlymenu>(0);
	private Set<Accessmenu> accessmenus = new HashSet<Accessmenu>(0);

	public User() {
	}

	public User(String staffid) {
		this.staffid = staffid;
	}

	public User(Role role, String staffid, String username, String userpassword, String email, Boolean islocked,
			Boolean status, Date createdate, String createby, Date updatedate, String updateby,
			Set<Commonlymenu> commonlymenus, Set<Accessmenu> accessmenus) {
		this.role = role;
		this.staffid = staffid;
		this.username = username;
		this.userpassword = userpassword;
		this.email = email;
		this.islocked = islocked;
		this.status = status;
		this.createdate = createdate;
		this.createby = createby;
		this.updatedate = updatedate;
		this.updateby = updateby;
		this.commonlymenus = commonlymenus;
		this.accessmenus = accessmenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "staffid", nullable = false, length = 15)
	public String getStaffid() {
		return this.staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	@Column(name = "username", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userpassword", length = 32)
	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "islocked")
	public Boolean getIslocked() {
		return this.islocked;
	}

	public void setIslocked(Boolean islocked) {
		this.islocked = islocked;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "createby", length = 15)
	public String getCreateby() {
		return this.createby;
	}

	public void setCreateby(String createby) {
		this.createby = createby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "updateby", length = 15)
	public String getUpdateby() {
		return this.updateby;
	}

	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Commonlymenu> getCommonlymenus() {
		return this.commonlymenus;
	}

	public void setCommonlymenus(Set<Commonlymenu> commonlymenus) {
		this.commonlymenus = commonlymenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessmenu> getAccessmenus() {
		return this.accessmenus;
	}

	public void setAccessmenus(Set<Accessmenu> accessmenus) {
		this.accessmenus = accessmenus;
	}

}
