package com.inter.info.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WfGroup generated by hbm2java
 */
@Entity
@Table(name = "wf_group", catalog = "interinfo")
public class WfGroup implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private String groupCode;
	private Set<WfNode> wfNodes = new HashSet<WfNode>(0);
	private Set<WfMember> wfMembers = new HashSet<WfMember>(0);

	public WfGroup() {
	}

	public WfGroup(String groupName, String groupCode, Set<WfNode> wfNodes, Set<WfMember> wfMembers) {
		this.groupName = groupName;
		this.groupCode = groupCode;
		this.wfNodes = wfNodes;
		this.wfMembers = wfMembers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GroupID", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GroupName", length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GroupCode", length = 100)
	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfGroup")
	public Set<WfNode> getWfNodes() {
		return this.wfNodes;
	}

	public void setWfNodes(Set<WfNode> wfNodes) {
		this.wfNodes = wfNodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfGroup")
	public Set<WfMember> getWfMembers() {
		return this.wfMembers;
	}

	public void setWfMembers(Set<WfMember> wfMembers) {
		this.wfMembers = wfMembers;
	}

}
