package com.inter.info.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WfNodetype generated by hbm2java
 */
@Entity
@Table(name = "wf_nodetype", catalog = "interinfo")
public class WfNodetype implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	private String typeRemarks;
	private Boolean typeStatus;
	private Set<WfNode> wfNodes = new HashSet<WfNode>(0);

	public WfNodetype() {
	}

	public WfNodetype(String typeName, String typeRemarks, Boolean typeStatus, Set<WfNode> wfNodes) {
		this.typeName = typeName;
		this.typeRemarks = typeRemarks;
		this.typeStatus = typeStatus;
		this.wfNodes = wfNodes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TypeID", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "TypeName", length = 100)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "TypeRemarks", length = 500)
	public String getTypeRemarks() {
		return this.typeRemarks;
	}

	public void setTypeRemarks(String typeRemarks) {
		this.typeRemarks = typeRemarks;
	}

	@Column(name = "TypeStatus")
	public Boolean getTypeStatus() {
		return this.typeStatus;
	}

	public void setTypeStatus(Boolean typeStatus) {
		this.typeStatus = typeStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfNodetype")
	public Set<WfNode> getWfNodes() {
		return this.wfNodes;
	}

	public void setWfNodes(Set<WfNode> wfNodes) {
		this.wfNodes = wfNodes;
	}

}
