package com.inter.info.model;

// Generated 2014-2-22 21:58:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WfNode generated by hbm2java
 */
@Entity
@Table(name = "wf_node", catalog = "interinfo")
public class WfNode implements java.io.Serializable {

	private Integer nodeId;
	private WfNodetype wfNodetype;
	private WfGroup wfGroup;
	private String nodeCode;
	private String nodeName;
	private Integer approverNum;
	private Boolean nodeStatus;
	private Set<WfLine> wfLinesForAfterNodeId = new HashSet<WfLine>(0);
	private Set<WfLine> wfLinesForBeforeNodeId = new HashSet<WfLine>(0);

	public WfNode() {
	}

	public WfNode(WfNodetype wfNodetype, WfGroup wfGroup, String nodeCode, String nodeName, Integer approverNum,
			Boolean nodeStatus, Set<WfLine> wfLinesForAfterNodeId, Set<WfLine> wfLinesForBeforeNodeId) {
		this.wfNodetype = wfNodetype;
		this.wfGroup = wfGroup;
		this.nodeCode = nodeCode;
		this.nodeName = nodeName;
		this.approverNum = approverNum;
		this.nodeStatus = nodeStatus;
		this.wfLinesForAfterNodeId = wfLinesForAfterNodeId;
		this.wfLinesForBeforeNodeId = wfLinesForBeforeNodeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NodeID", unique = true, nullable = false)
	public Integer getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Integer nodeId) {
		this.nodeId = nodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NodeTypeID")
	public WfNodetype getWfNodetype() {
		return this.wfNodetype;
	}

	public void setWfNodetype(WfNodetype wfNodetype) {
		this.wfNodetype = wfNodetype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID")
	public WfGroup getWfGroup() {
		return this.wfGroup;
	}

	public void setWfGroup(WfGroup wfGroup) {
		this.wfGroup = wfGroup;
	}

	@Column(name = "NodeCode", length = 100)
	public String getNodeCode() {
		return this.nodeCode;
	}

	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	@Column(name = "NodeName", length = 100)
	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	@Column(name = "ApproverNum")
	public Integer getApproverNum() {
		return this.approverNum;
	}

	public void setApproverNum(Integer approverNum) {
		this.approverNum = approverNum;
	}

	@Column(name = "NodeStatus")
	public Boolean getNodeStatus() {
		return this.nodeStatus;
	}

	public void setNodeStatus(Boolean nodeStatus) {
		this.nodeStatus = nodeStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfNodeByAfterNodeId")
	public Set<WfLine> getWfLinesForAfterNodeId() {
		return this.wfLinesForAfterNodeId;
	}

	public void setWfLinesForAfterNodeId(Set<WfLine> wfLinesForAfterNodeId) {
		this.wfLinesForAfterNodeId = wfLinesForAfterNodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wfNodeByBeforeNodeId")
	public Set<WfLine> getWfLinesForBeforeNodeId() {
		return this.wfLinesForBeforeNodeId;
	}

	public void setWfLinesForBeforeNodeId(Set<WfLine> wfLinesForBeforeNodeId) {
		this.wfLinesForBeforeNodeId = wfLinesForBeforeNodeId;
	}

}
